name: xiaomi_hackathon
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  badges: ^2.0.3
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^3.4.2
  flutter_staggered_animations: ^1.1.1
  paytm: ^3.0.1
  http: ^0.13.5
  paytm_allinonesdk: ^1.1.8
  cloud_firestore: ^3.3.0
  firebase_core: ^1.19.2
  firebase_database: ^9.0.19
  carousel_slider: ^4.1.1
  mailer: ^5.2.0
  pay: ^1.0.10
  card_swiper: ^2.0.4
  im_stepper: ^1.0.1+1
  url_launcher: ^6.1.5
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/phoneCat.png
    - assets/images/laptopCat.png
    - assets/images/earphoneCat.png
    - assets/images/bagCat.png
    - assets/images/smartHomeCat.png
    - assets/images/tvCat.png
    - assets/images/smartphone.png
    - assets/icons/
