name: xiaomi_hackathon
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  badges: ^2.0.3
  curved_navigation_bar: ^1.0.3
  flutter_barcode_scanner: ^2.0.0
  another_stepper: ^1.0.4
  razorpay_flutter: ^1.3.2
  carousel_slider: ^4.1.1
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fluttertoast: ^8.0.9
  connectivity_plus: ^2.3.7
  internet_connection_checker: ^0.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^3.4.2
  flutter_staggered_animations: ^1.1.1
  http: ^0.13.5
  cloud_firestore: ^3.3.0
  firebase_core: ^1.19.2
  firebase_database: ^9.0.19
  mailer: ^5.2.0
  card_swiper: ^2.0.4
  im_stepper: ^1.0.1+1
  url_launcher: ^6.1.5
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
